### ISSUE TITLE
STLDR file not generated

### ISSUE THREAD

**Issue by MyVanitar** [kotetsuy/STLDR#2]
Hi,

I have copied the `Dev_Inf.c`, `Loader_Src.c` and headers into my project (which uses the QSPI library of your repo: https://github.com/kotetsuy/TouchGFXDemo), however after bulding it, it does not generate the `STLDR` file. 

I use STM32CubeIDE

**Comment by kotetsuy** [comment]
Hi,

Probably, you misunderstand. The STLDR is not included TouchGFXdemo.
The STLDR is a separated program to write QSPI.

**Comment by kotetsuy** [comment]
1) Build hex file on TouchGFX.
2) Build STLDR.
3) Install STLDR in STM32CubeProgrammer.
4) Write all hex file by using STM32CubeProgrammer.

**Comment by MyVanitar** [comment]
Hi

Should I split the HEX file (always) because of your mentioned reason?

If yes, should I change the starting address with each HEX file?

**Comment by MyVanitar** [comment]
> 2. Build STLDR

I use STM32CubeIDE. it seems I should replace the extension of the `*.elf` file with `*.stldr`, is there any other method?

**Comment by kotetsuy** [comment]
Hi,

Please read the manual of STM32CubeProgrammer.
https://www.st.com/content/ccc/resource/technical/document/user_manual/group0/76/3e/bd/0d/cf/4d/45/25/DM00403500/files/DM00403500.pdf/jcr:content/translations/en.DM00403500.pdf

Also, you need to rename *.elf to *.stldr.

I think that this thread in ST community is useful for you.

https://community.st.com/s/question/0D53W00000pRYKlSAO/custom-external-loader-can-pass-the-test-but-doesnt-work-with-stm32cubeprogrammer

**Comment by MyVanitar** [comment]
Should I split the HEX file (always) because of your mentioned reason, here (https://github.com/kotetsuy/STLDR/tree/master/HexSplitter)?

If yes, should I change the starting address for each HEX file when I program each one?

**Comment by kotetsuy** [comment]
First answer is yes.
Second answer is no. You don't need to change start address.

**Comment by MyVanitar** [comment]
Thanks
